### ISSUE TITLE
ng2 option isn't possible to select when user selects "client only app"

### ISSUE THREAD

**Issue by vitkrv** [ericmdantas/generator-ng-fullstack#105]
Hi, I want to share my observation. I have downloaded latest release _(v1.7.1)_ and try to setup new project.
I wrote the name of project, name from Github and chose _'client'_ option. Then I couldn't choose _'ng2'_, because arrows didn't work.
For option _'fullstack'_ all works fine.

**Comment by ericmdantas** [comment]
Hello, @vitkrv!

This bug is a special kind, I've seen it before but couldn't fix it - it's more likely a yeoman bug. 

Anyway, for now, when you get to choose `client` and `ng2` you can type `ng2` instead of selecting it, it'll work the same.

I'll leave the issue open in case we find some fix.

PS: What OS are you using, by the way?

**Comment by ericmdantas** [comment]
Not happening on OS X.

**Comment by ericmdantas** [comment]
Well, since it's a bug with Yeoman, I'll suggest we open an issue there - there's really not much I can do here, I guess.

**Comment by ericmdantas** [comment]
Updating yeoman with `npm i -g yo` solved the problem.

**Comment by vitkrv** [comment]
Thanks for help.
