### ISSUE TITLE
Generic Git URL support

### ISSUE THREAD

**Issue by rahulswaminathan** [ericmdantas/generator-ng-fullstack#152]
Hello @ericmdantas,
         As currently the git url references are hard coded to github, I was thinking of a feature where the user can enter a git url of their choice like BitBucket or a private git repo. This would essentially replace/add to the username prompt. Please let me know what you think and I can help on this.

Regards,
Rahul Swaminathan

**Comment by ericmdantas** [comment]
Hey there, @rahulswaminathan.

That's definitely something I've wanted to do for some time now, but it either always falls short because of time, or I forget about it. I'll label it as a priority for 1.9, so it makes it this time.

As for the options, I've thought about the following:
- github.com;
- gitlab.com;
- bitbucket.org;

Anything else you'd like to add?

**Comment by rahulswaminathan** [comment]
I was thinking you can have three prompts:

**1. Type of Repository: [GitHub, BitBucket, Other]**
In case the choice is other, 
**1a. Enter your git URL: [_http://yourservername:port_]**
_(This is because gitlab installations can have the URL with the server's hostname)_
**2. Namespace:**
**3. Appname:**

So, the final git url would be _repo/namespace/appname.git_

What do you think?

**Comment by ericmdantas** [comment]
Sounds good, with a small change.

Maybe we could have the Git servers as: Github, BitBucked and GitLab. And, if the user chooses GitLab, we ask him if it's on GitLab's cloud or somewhere else - and then ask the URL, namespace, app name, etc.

**Comment by rahulswaminathan** [comment]
Sure, sounds good. Do let me know if you need my help with code.

**Comment by ericmdantas** [comment]
Feel free to give it a shot and submit a PR - there's no need to be a complete one, can be a WIP. :smile:  

I'll create a branch for `1.9` today so we can target it instead of master. 

Just for sanity check, here are some places to be changed:
- Golang import paths;
- `.yo-rc.json` would have to have a "gitServer" (not sure if we'd call it explicitly "git", though) set to "github.com", "gitlab.com", "bitbucket.org" or "CUSTOM_DOMAIN:PORT" .
- README.md uses the url for the badges;
- package.json uses the url for repository, bugs and homepage fields;
- bower.json also uses it for homepage.

**Comment by ericmdantas** [comment]
Branch 1.9 created:

https://github.com/ericmdantas/generator-ng-fullstack/tree/v1.9

**Comment by rahulswaminathan** [comment]
I was thinking of another approach where the user enters his **username, email** (only once and then it can be stored as default values) and then a remote URL like **http://repository/namespace/appname.git**. This URL can be split on **"/"** into separate variables and then use wherever we want. This can also be used to set **local** _git config_ and _git remote_ for the new app.

I know I'm changing designs but just wanted to throw it open for discussion before I start. I'm okay with either solutions.

**Comment by ericmdantas** [comment]
Even though I like the idea of having one information being split in many, I think that'd not be good/fast for the user who's using a known service. What you're suggesting might fit perfectly where the user chose a custom git server, though.

As for `username`/`email` info, we already store the `username` in `.yo-rc.json`, we can easily add `email` there too.

**Comment by ericmdantas** [comment]
Implemented in #164.
