### ISSUE TITLE
App Structure

### ISSUE THREAD

**Issue by ccocker** [ericmdantas/generator-ng-fullstack#168]
It would be a nice enhancement to provide a starting point that includes a main component and then a navigation component that directs you to the todo component, rather than using the todo component as the starting point.

**Comment by Abdizriel** [comment]
I agree with you @ccocker also I would change folder structure in client to be more like in angular2 style guide

I mean to create todo directory which would have:
- todo.component.ts
- todo.service.ts
- todo.css
- todo.html

and create app.component.ts which would start todo.component.ts

Similar solution could be done in NodeJS server API. Instead of creating directories like dao, model etc. you can just create directory todo with:
- index.js (routes)
- todo.controller.js
- todo.dao.js
- todo.model.js

And in case of server I do not know if it wont be better to remove server directory from tests and add specific files to api directory like:
- index.spec.js
- todo.controller.spec.js
- todo.dao.spec.js
- todo.model.spec.js

**Comment by Abdizriel** [comment]
@ericmdantas, Ok, I understand idea of "deep" path for server but it doesn't include Angular2 where we should build components smaller components and build bigger ones. 

I will create issue and I'll take care with that task.

**Comment by ericmdantas** [comment]
Awesome!

**Comment by ericmdantas** [comment]
I'm closing this in favor of #203.
