### ISSUE TITLE
Roadmap to 1.10

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/generator-ng-fullstack#202]
_This is a live document_

There are many new stuff coming in 1.9, but we'd have no time to attack all the possibilities, so we'll release the essential and make the improvements as we go. 

The 1.10 version is meant to make those improvements and fix most, if not all, of the rough edges.

This is what we have for 1.10:
- [x] Clean project (#211);
- [ ] Flat structure (#203);
- [ ] Option to work with WebPack (#201);

**Comment by ericmdantas** [comment]
Adds option for clean project.

**Comment by ntanitime** [comment]
The support for use WebPack would be amazing!

**Comment by divanvb** [comment]
ETA on release for clean project?

**Comment by ericmdantas** [comment]
Hello, @divanvb. I'm sorry, but what does ETA mean? 

I'm stuck at a couple bugs in v1.9, so, if you have time, I could merge the clean project issue into v1.9 and we could release alphas and betas with it. What do you think?

**Comment by divanvb** [comment]
@ericmdantas, ETA = Estimated Time of Arrival so basically when the next version will be released that includes a clean project option.

Ah okay, I think that would be a good idea because I'm sure there are quite a few people that would prefer the bare basics of the generator creating only the necessary files instead of having to go and remove the default Todo application from the generated project. But it's up to you to decide what is best :)

**Comment by ericmdantas** [comment]
Sure, even I need that every project. I'll make it available for 1.9 then.

As for the client and server stuff, I'm thinkin about leaving the `client/dev/index.html` and `server/index.js`. Sounds good?

**Comment by divanvb** [comment]
@ericmdantas, yeah sounds good to me :dancing_men:

**Comment by ericmdantas** [comment]
Clean project feature released under `1.10.0-0`.

Download it by running `npm i -g generator-ng-fullstack@next`.

**Comment by countrdd** [comment]
so it 203 implemented?

**Comment by ericmdantas** [comment]
`1.10` became `v2`.
