### ISSUE TITLE
Generating Clean Project

### ISSUE THREAD

**Issue by EmmanuelObo** [ericmdantas/generator-ng-fullstack#211]
I think it would be good if there was an option to create a clean Project that has all the basic routers set up and allows the user to build their project from (almost) scratch. Because maybe some people already have a hang of the fullstack project structure, don't want to have to spend time removing the todo app and creating their project.

**Comment by ericmdantas** [comment]
I've been thinking about it for a while, sounds good.

**Comment by EmmanuelObo** [comment]
Yea I think it will be a good addition.

**Comment by ericmdantas** [comment]
Are there any files that should still exist even when generating a clean project? 

Something like `client/dev/index.html`, `client/dev/app.js` and `server/index.js` - for example. Just wondering because it might be good to make the user remember the proposed folder structure, so he/she doesn't have to touch too many files to get the static server, build and other stuff to work.

**Comment by ericmdantas** [comment]
ping @divanvb because of previous interest in the `clean project` feature

**Comment by ericmdantas** [comment]
Released under `1.10.0-0`. 

Download it by running `npm i -g generator-ng-fullstack@next`.
