### ISSUE TITLE
@Next

### ISSUE THREAD

**Issue by bernardbr** [ericmdantas/generator-ng-fullstack#267]
Hi!
Could you release the next version with ng1 component feature and the option to create without example as a "final" version 1.10?

**Comment by ericmdantas** [comment]
Yup.

**Comment by bernardbr** [comment]
Thanks! :clap:

**Comment by ericmdantas** [comment]
Done.

Can you please give it a try?

**Comment by bernardbr** [comment]
Off course!
Wait a minute please...

**Comment by bernardbr** [comment]
The version 1.9.10 still create a todo's example. It's correct?

**Comment by ericmdantas** [comment]
Yes, the version that has an option not to create it has to be installed as `npm i -g generator-ng-fullstack@next`.

**Comment by bernardbr** [comment]
Oh! Ok... 
This one is stable?
I'm directing my team to use the generator, but I'm afraid of the @next version don't be stable.

**Comment by ericmdantas** [comment]
It is. It was created to help people use new features without having to wait for a long time before the whole version is done.

It's pretty much the current version (`@latest`) with a few new implementations from the next roadmap.

Every bug fixed in the `master` branch is fixed in the `next` branch too. As of right now, the only difference between `master` and `next` is the possibility to generate clean projects. 

When the `next` branch is done, in this case `v1.10`, it'll be fully merged into `master` and be installed the normal way.

**Comment by bernardbr** [comment]
I get it! Thanks.

**Comment by ericmdantas** [comment]
:+1:
